# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5eb041c46fa69f8c00a0e6d027df42a8b597e5f75891490e29367713b920c5271b04519b5349497ea41dbe1a6973ecb4aadd0e2a79a71cd5a2842efafecbf70f

test:
  secret_key_base: f3320eb3e2cb017a4f6c0199e77c42f5b4ab6793e7c2fe9fc4826a33a56e8d8a4d9f5a4f76746ca51dde9f5e07c84194f342ca817d26c1b71ddd12b080fc7fc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
